### ISSUE TITLE
Textarea class not found.

### ISSUE THREAD

**Issue by gassius** [marvinlabs/laravel-html-bootstrap-4#11]
When using bs()->textarea() 

 Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Class 'Spatie\Html\Elements\TextArea' not found

Error on /vendor/marvinlabs/laravel-html-bootstrap-4/src/Bootstrap/Elements/TextArea.php:17

Spatie deinfe the class as Textarea, not cap on first A

**Comment by vpratfr** [comment]
Sorry about that. Windows FS did it again
