### ISSUE TITLE
Horizontal Form

### ISSUE THREAD

**Issue by jyhsu2000** [marvinlabs/laravel-html-bootstrap-4#12]
I would like to know if it support [Horizontal Form](https://getbootstrap.com/docs/4.0/components/forms/#horizontal-form) or not.
Does it? Or will it?

**Comment by vpratfr** [comment]
Hi,

According to that documentation, horizontal forms are just standard forms with some markup for the grid.

You can already implement these horizontal forms with the library.

What exactly would you need on top of the current features?

**Comment by vpratfr** [comment]
I think I got what you meant. I have added some functions to form groups to allow easy creation of horizontal rows. Open a new issue if needed. Closing this one for now.

**Comment by jyhsu2000** [comment]
What I hope is that there will be a function `openHorizontalForm()` like `openForm()`, but it's for horizontal form.
We can use this function to create a horizontal form easily, 
instead of adding class in each `div`, `label` and `input` manually.

There is a similar example from [BootForms #horizontal-forms](https://github.com/adamwathan/bootforms#horizontal-forms)

**Comment by vpratfr** [comment]
Yes but that was Bootstrap 3, which had a different approach to horizontal forms. 

I guess with a more general feature we could however address this issue (and a few others at the same time) in a clean and reusable way. See #14.

**Comment by vpratfr** [comment]
Will try to get that in 0.5.0. If you have a PR or suggestion, feel free to submit ;)

**Comment by vpratfr** [comment]
Can you give some ideas on #14 or #15? How does that look to you?

**Comment by vpratfr** [comment]
With #15 it becomes much simpler. Here is some sample code to automatically produce a row:

BEFORE

        {{-- Manually create a row --}}
        {{ bs()->formGroup(bs()->text('first_name', 'John'))
                ->wrapControlIn(bs()->div()->addClass('col-sm-10'))
                ->label('First name', false, ['col-sm-2'])
                ->addClass('row')}}

AFTER

        {{-- Create a row using the default configuration entry: config('bs4.form_rows.default') --}}
        {{ bs()->formGroup(bs()->inputGroup(bs()->text('username', 'johndoe'), '@'))
                ->label('Username', false)
                ->showAsRow() }}

        {{-- Create a row using a custom configuration entry: config('bs4.form_rows.no_label') --}}
        {{ bs()->formGroup(bs()->checkBox('remember', 'Remember me'))
                ->label('Remember me', true)
                ->showAsRow('no_label')}}

        {{ bs()->formGroup(bs()->submit('Submit', 'secondary')->child(fa()->icon('send')->addClass('ml-2')))
                ->showAsRow('centered')}}

**Comment by jyhsu2000** [comment]
Awesome.
I think `showAsRow()` is good enough.
Thank you for updating so quickly.

**Comment by vpratfr** [comment]
No worries. I need it for a client so I am looking for ease of use too.
