### ISSUE TITLE
Data bind

### ISSUE THREAD

**Issue by weijinnx** [marvinlabs/laravel-html-bootstrap-4#17]
Will be cool to have an opportunity to bind model data to form, for update record.

**Comment by vpratfr** [comment]
Is not that already available?

See: https://github.com/marvinlabs/laravel-html-bootstrap-4/blob/master/src/Bootstrap/Traits/BuildsForms.php#L42

Pass a 'model' element to the options array.

And name the inputs similarly to the model attribute.

**Comment by weijinnx** [comment]
Yes, I found it. Thanks! But it would be great to add this to documentation, for future users.

**Comment by vpratfr** [comment]
You can make a pull request for documentation too. That would be very much appreciated. (PR always on the develop branch please).

Also note that I have not yet tested model binding extensively. Do not hesitate to report any strange behaviour. Will fix as quickly as possible.

**Comment by vpratfr** [comment]
A proper doc folder with some MD files in there would make for a decent wiki/documentation if you wish to start with it.
