### ISSUE TITLE
Form with enctype

### ISSUE THREAD

**Issue by weijinnx** [marvinlabs/laravel-html-bootstrap-4#18]
Hey! Maybe I do something wrong, but when I add `'files' => true` to options array for form, nothing happens... I saw sources, no code for this option. Need to add it.

**Comment by vpratfr** [comment]
Will do when I get back to office. In the meantime feel free to submit a PR on the develop branch if you want.

Thanks for the report.

**Comment by vpratfr** [comment]
Can you test code in PR #19 ? That should work.

**Comment by vpratfr** [comment]
Fixed. Will be in next release.
