### ISSUE TITLE
Validation Errors do not show up when form is opened inside a blade layout

### ISSUE THREAD

**Issue by JamesPoel** [marvinlabs/laravel-html-bootstrap-4#25]
Hi
This is great, but how do you show validation errors against the fields? (.is-invalid, .invalid-feedback etc?)
I see references to it within the package, but I can't find any example of implementing it.
Thanks

**Comment by vpratfr** [comment]
You should not have anything special to do. Errors will be shown automatically when returning to the form (package checks old input and errors).

You have sample usage on my [package workbench project](https://github.com/marvinlabs/laravel-workbench):

- https://github.com/marvinlabs/laravel-workbench/blob/master/resources/views/laravel-html-bootstrap-4/form.blade.php
- https://github.com/marvinlabs/laravel-workbench/blob/master/routes/web.php#L30

**Comment by JamesPoel** [comment]
Ah, I've found the issue.

The errors don't show up if you open the form in another blade file and then include the fields with blade @yield

This is because formState (ln 38 of Input.php, for example) is set to null when the form is built this way - which causes ln 78-79 to be falsey.

E.g.

```
page 1:
{{ bs()->openForm('post', '/' ) }}
@yield( 'form' )
{{ bs()->closeForm() }}
```

page 2:
```
@extends( 'page1' )
@section( 'form' )
        {{ bs()->formGroup( bs()->text( 'test' ) )->label( 'Test' ) }}
@endsection
```
Could this perhaps be looked into?

**Comment by vpratfr** [comment]
Hi,

Looks like in that case, closeForm is called before the section content is even inserted.

Not sure if that can be fixed as it seems to be how layouts work in Blade.

Would be happy to accept a PR if you find a fix.

**Comment by vpratfr** [comment]
Closing this for now, if you have a PR to fix that, I'd review it happily.

**Comment by JamesPoel** [comment]
A rubbish workaround, but this works.
If you call `bs()->openForm( ... )` in the parent view, but call `bs()->closeForm()` in the child view, the validation works.
