### ISSUE TITLE
Can't set disabled() on radioGroup

### ISSUE THREAD

**Issue by axyr** [marvinlabs/laravel-html-bootstrap-4#33]
Thanks for adding the radio and radioGroup elements!

In the RadioGroup __call method are some methods that will be forwarded to the Radio elements, but`disabled` is not one of them:

```
['radio' => '', 'forgetRadio' => 'forget', 'addRadio' => 'add']
```

There is some magic in the __call method I did not understand, but it not seems a matter of adding `disabled` (and 'readonly') to the array.

**Comment by vpratfr** [comment]
Hi

Magic allows to call methods on the radios in the group.

Try `group->radioDisabled()`

**Comment by axyr** [comment]
Ah thanks!
