### ISSUE TITLE
Labels can not contain html

### ISSUE THREAD

**Issue by axyr** [marvinlabs/laravel-html-bootstrap-4#34]
When adding an 'accept terms' checkbox you can not add a link to a Terms & Conditions page/doc

```
 {{ bs()->formGroup(bs()->checkBox('accept_terms', 'I agree with the <a href="/terms" target="_blank">Terms & Conditions</a>'), '') }}
```

`MarvinLabs\Html\Bootstrap\Elements\CheckBox::label()` uses:

```
 ->text($element->description)
```

This probably can be replaced with : ?

```
 ->html($element->description)
```

**Comment by vpratfr** [comment]
Hi

Can you post a PR about this? Change could be made to radio buttons too.

**Comment by axyr** [comment]
fixed with https://github.com/marvinlabs/laravel-html-bootstrap-4/pull/36
