### ISSUE TITLE
Multi-Select support?

### ISSUE THREAD

**Issue by JamesPoel** [marvinlabs/laravel-html-bootstrap-4#37]
Could you add multi-select support to a future release?
I can `->attribute('multiple')` on a select, but I can't pass an array as the values.
Thanks 💯

**Comment by vpratfr** [comment]
It is already supported.

```$php
{{ bs()->select('countries', ['FR' => 'France', 'S' => 'Sweden', 'P' => 'Portugal'])
       ->multiple()
       ->value(['P', 'FR']}}
```
