### ISSUE TITLE
Radio Group doesn't repopulate correctly

### ISSUE THREAD

**Issue by RTC1** [marvinlabs/laravel-html-bootstrap-4#40]
` 
{{ bs()->formGroup()->label('Is 1=1?')
                                        ->control(
                                            bs()->radioGroup('smaller_sizes', [
                                                'Y' => 'Yes',
                                                'N' => 'No'
                                            ])
                                        )
                                    }}
`

If the form errors, both radios are marked as 'checked'.  Fixed in #41

**Comment by RTC1** [comment]
This should also resolve #39.

**Comment by vpratfr** [comment]
Should be fixed with 1.6.0. Do not hesitate to re-open with some additional info to reproduce.
