### ISSUE TITLE
old() function does not work with arrays

### ISSUE THREAD

**Issue by JamesPoel** [marvinlabs/laravel-html-bootstrap-4#47]
Example:

```
{{ bs()->text('profile[first_name]', $user->first_name) }}
```

If you submit a form containing the above, and there is a validation error, the value previously inputted into the form is not loaded back into the field.

Caused by [ln 31 of OldFormInputProvider.php](https://github.com/marvinlabs/laravel-html-bootstrap-4/blob/c2f16336fb502d3316a64cb7955a7efe0b75bc14/src/Bootstrap/Forms/OldFormInputProvider.php#L31).
`return $this->request->old(field_name_to_id($key), $default);`

`field_name_to_id($key)` translates to `"profile_first_name"`, wheras it should be `"profile.first_name"`.

Changing the line to simply `return $this->request->old($key, $default);`, solves the issue.

**Comment by vpratfr** [comment]
Hi,

would you be able to submit a PR for a fix?

**Comment by JamesPoel** [comment]
Done

**Comment by JamesPoel** [comment]
Still not merged, causing a fair bit of problems :( Had to edit the file directly for now... ha
