### ISSUE TITLE
Not working with latest spatie html lib 2.20.0

### ISSUE THREAD

**Issue by wvdongen** [marvinlabs/laravel-html-bootstrap-4#49]
See https://github.com/spatie/laravel-html/blob/master/CHANGELOG.md#2200---2019-01-18.

Fatal error: Access level to MarvinLabs\Html\Bootstrap\Elements\Traits\SizableComponent::size() must be public (as in class Spatie\Html\Elements\Input)

**Comment by yusidabcs** [comment]
Fast fix is just change from `protected function size($size)` to `public function size($size)`

**Comment by vpratfr** [comment]
Hi

I would happily accept a PR.

**Comment by PaulMenheere** [comment]
Here you go..
