### ISSUE TITLE
Add CI service

### ISSUE THREAD

**Issue by peter279k** [marvinlabs/laravel-html-bootstrap-4#60]
As title, I think it's good to use GitHub Action  to be the CI service.

I can do for that once the repository owner accepts that :).

**Comment by vpratfr** [comment]
Where do you enable that?

**Comment by peter279k** [comment]
You can enable this via this [link](https://github.com/marvinlabs/laravel-html-bootstrap-4/actions) and adding the `YAML` file on `.github/workflows` folder.

If you want to do that, I can help you to accomplish this :).

**Comment by vpratfr** [comment]
There you go: https://github.com/marvinlabs/laravel-html-bootstrap-4/tree/master/.github/workflows

**Comment by vpratfr** [comment]
(I used the laravel template)
